server:
  port: 0

spring:
  application:
    name: authentication-service
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
